fix(urd): emits event in constructor
morpho-org/universal-rewards-distributor pull request #82
Opened 2023-10-28 18:04 UTC by julien-devatom

[Cantina issue](https://github.com/cantinasec/review-morpho-blue-1/issues/76)

2023-10-30 12:13 UTC, Rubilmax approved these changes

2023-10-30 20:12 UTC, QGarchery reviewed
I think that this would fix #73, because it would become consistent (event are always emitted). What about removing the owner, timelock, root, and ipfsHash arguments to the UrdCreated event though ?

2023-10-31 10:17 UTC, Jean-Grimal approved these changes

2023-10-31 10:59 UTC, julien-devatom commented
> I think that this would fix #73, because it would become consistent (event are always emitted). What about removing the owner, timelock, root, and ipfsHash arguments to the UrdCreated event though ?

The problem is that URD constructor events are emitted **before** the factory event. It means that you are not tracking the URD event of the constructor when they are cast. Another solution would be to move the Factory event at the beginning of the function (and we need to precompute the urd address)

2023-10-31 13:31 UTC, QGarchery requested changes
> The problem is that URD constructor events are emitted before the factory event

Oh I did not realize that. It's weird to have events that are not used (and also the pending root should actually not emit any event in the constructor). Then I think the easiest solution is to just unfactorize the `_set*` functions in the URD constructor, this is only adding one line of code and no real duplication tbh

2023-10-31 13:53 UTC, Rubilmax commented
Why aren't we removing the redundant data from the `UrdCreated` event instead? I don't think they bring much value

2023-10-31 14:11 UTC, MerlinEgalite commented
> Why aren't we removing the redundant data from the `UrdCreated` event instead? I don't think they bring much value, because they are only temporary

💯 let's do that

2023-10-31 14:13 UTC, julien-devatom commented
> Why aren't we removing the redundant data from the `UrdCreated` event instead? I don't think they bring much value, because they are only temporary

For the same reason explained as before:
The problem is that URD constructor events are emitted before the factory event. 

In fact, when you're indexing from a factory, you start indexing a new contract on `UrdCreated` event. So the indexing mechanism cannot handle the events emitted before. 


However, they are still useful if you are indexing only the URD contract, and that you know in advance the contract address.

2023-10-31 14:21 UTC, MerlinEgalite commented
But we can just put events before the construction no?

2023-10-31 14:34 UTC, Rubilmax commented
> > Why aren't we removing the redundant data from the `UrdCreated` event instead? I don't think they bring much value, because they are only temporary
> 
> For the same reason explained as before: The problem is that URD constructor events are emitted before the factory event.
> 
> In fact, when you're indexing from a factory, you start indexing a new contract on `UrdCreated` event. So the indexing mechanism cannot handle the events emitted before.
> 
> However, they are still useful if you are indexing only the URD contract, and that you know in advance the contract address.

Alright then I understand that having redundant data serves 2 purposes and that both cases are useful so we should simply acknowledge the issue and do nothing?

2023-10-31 15:11 UTC, julien-devatom commented
> Or we can pre-calculate the URD address and simply emit it along the caller in UrdCreated before but I find it ugly


Yeah its weird.. I prefer to keep the 2 events.

2023-10-31 15:58 UTC, QGarchery commented
Just doing `owner = newOwner` (and the like) instead of `_setOwner(newOwner)` in the constructor is also a solution, and it seems easy enough

2023-10-31 16:05 UTC, Rubilmax commented
> Just doing `owner = newOwner` (and the like) instead of `_setOwner(newOwner)` in the constructor is also a solution, and it seems easy enough

There's a purpose for it too: being able to have access to the initial value of `owner` at construction via `OwnerSet` events emitted from the URD
Otherwise as an integrator you need to also look for the `UrdCreated` event in the factory, which is cumbersome

2023-10-31 16:08 UTC, QGarchery commented
> There's a purpose for it too: being able to have access to the initial value of owner at construction via OwnerSet events emitted from the URD

Alright, alright, let's keep it :D

2023-10-31 16:09 UTC, QGarchery approved these changes

2023-10-31 18:38 UTC, MerlinEgalite approved these changes
Just realized that the contract would have inherited from `Ownable` from OZ

2023-10-31 18:55 UTC, QGarchery commented
> Just realized that the contract would have inherited from Ownable from OZ

You mean "could have" right ?

2023-11-01 15:36 UTC, julien-devatom commented
> Just realized that the contract would have inherited from `Ownable` from OZ

Already discussed in #44

2023-11-01 18:17 UTC, MerlinEgalite commented
> > Just realized that the contract would have inherited from `Ownable` from OZ
> 
> Already discussed in #44

Now that there's the version 0.5 of OZ I think we don't have our problem anymore

2023-11-03 11:33 UTC, MerlinEgalite commented
Fixed by https://github.com/morpho-org/universal-rewards-distributor/pull/82

2023-11-03 12:06 UTC, Rubilmax approved these changes

2023-11-03 12:06 UTC, Rubilmax commented on test/UniversalRewardsDistributorTest.sol
>      }
We could merge these 2 tests into a single one, testing all events
It avoids having to repeat the test case

2023-11-04 16:27 UTC, merged