fix: downgrade to 0.8.19
morpho-org/universal-rewards-distributor pull request #86
Opened 2023-10-28 20:12 UTC by julien-devatom

[Cantina issue](https://github.com/cantinasec/review-morpho-blue-1/issues/74)

2023-10-30 17:02 UTC, QGarchery requested changes
While we are at it, I would suggest changing the pragma of the interface too. Basically, there is no reason to restrict pragmas based on new features that it provides, so it should be based on bugfixes and breaking changes. See full discussion [here](https://morpholabs.slack.com/archives/C02N7CSP91C/p1694789792144889)

2023-10-31 09:30 UTC, Rubilmax approved these changes

2023-10-31 10:45 UTC, Jean-Grimal approved these changes

2023-10-31 12:28 UTC, QGarchery approved these changes

2023-10-31 13:18 UTC, MerlinEgalite approved these changes

2023-11-04 16:29 UTC, merged