Use a struct in the PendingRootSet event
morpho-org/universal-rewards-distributor pull request #89
Opened 2023-10-31 15:47 UTC by QGarchery

2023-11-01 18:34 UTC, MerlinEgalite approved these changes

2023-11-06 08:45 UTC, julien-devatom requested changes
I'm against it since fields are not indexed, this is specially why Ive destructured the event

2023-11-06 09:12 UTC, MerlinEgalite commented
> I'm against it since fields are not indexed, this is specially why Ive destructured the event

Good point.

Though I think the renaming for the constructor parameters is a good idea

2023-11-06 09:21 UTC, julien-devatom commented
> > I'm against it since fields are not indexed, this is specially why Ive destructured the event
> 
> Good point.
> 
> Though I think the renaming for the constructor parameters is a good idea

Handled in  #99 
So I close the PR

2023-11-06 09:21 UTC, closed without merging